name: narino_travel_food
description: "Discover the best destinations, restaurants and unique experiences in Nariño - Your complete travel and food guide"
publish_to: 'none'

version: 2.0.0+3

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Dependencias de Firebase (versiones estables)
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.15.10
  
  # Paquete de iconos (Necesario para FontAwesomeIcons)
  font_awesome_flutter: ^10.7.0
  
  # Mapas GRATUITOS - OpenStreetMap
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  location: ^5.0.0
  geolocator: ^10.1.0
  
  # Para abrir URLs (Google Maps)
  url_launcher: ^6.2.2
  
  # Para favoritos y persistencia
  shared_preferences: ^2.2.2
  
  # Para compartir contenido
  share_plus: ^7.2.2
  
  # Para fechas relativas (hace 2 días, etc.)
  timeago: ^3.6.1
  flutter_localizations:
    sdk: flutter
  translator: ^1.0.4+1

dev_dependencies:
  intl_utils: ^2.8.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  cupertino_icons: ^1.0.2


flutter:
  uses-material-design: true
  generate: true
  # Declaración de assets para incluir la carpeta de imágenes
  assets:
    - assets/images/

l10n:
  arb-dir: lib/l10n
  template-arb-file: app_es.arb
  output-localization-file: app_localizations.dart
  output-class: AppLocalizations